// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9TvkzTBFGjxbgDklwmeYZgYi7RWkVDW8',
    appId: '1:805057311276:web:283172abba80e79dddd789',
    messagingSenderId: '805057311276',
    projectId: 'spotifyclone1997',
    authDomain: 'spotifyclone1997.firebaseapp.com',
    storageBucket: 'spotifyclone1997.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrYWAVIWvVxYCXMi3gTkKD8BUeyeZ_d-8',
    appId: '1:805057311276:android:847a4faca0e3cdc0ddd789',
    messagingSenderId: '805057311276',
    projectId: 'spotifyclone1997',
    storageBucket: 'spotifyclone1997.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtr5L2oDQHpeuRXTmT_V1s-n9Lv_2ZeeM',
    appId: '1:805057311276:ios:005b976702a16574ddd789',
    messagingSenderId: '805057311276',
    projectId: 'spotifyclone1997',
    storageBucket: 'spotifyclone1997.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtr5L2oDQHpeuRXTmT_V1s-n9Lv_2ZeeM',
    appId: '1:805057311276:ios:005b976702a16574ddd789',
    messagingSenderId: '805057311276',
    projectId: 'spotifyclone1997',
    storageBucket: 'spotifyclone1997.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9TvkzTBFGjxbgDklwmeYZgYi7RWkVDW8',
    appId: '1:805057311276:web:7cbfbf03e604024fddd789',
    messagingSenderId: '805057311276',
    projectId: 'spotifyclone1997',
    authDomain: 'spotifyclone1997.firebaseapp.com',
    storageBucket: 'spotifyclone1997.firebasestorage.app',
  );
}
